<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Saurabhs-MacBook-Pro.local" ignored="0" name="Test" tests="2" failures="1" timestamp="2019-12-06T23:51:32 EST" time="12.474" errors="0">
  <testcase name="loginTest" time="5.804" classname="com.testcases.fail.TC001_LoginTest"/>
  <testcase name="VerifyAddPayee" time="5.571" classname="com.testcases.fail.TC003_VerifyAddPayee">
    <failure type="java.lang.AssertionError" message="expected [The new payee HydroOne Utility was successfully created.] but found [The new payee HydroOne Utility was successfully created.test]">
      <![CDATA[java.lang.AssertionError: expected [The new payee HydroOne Utility was successfully created.] but found [The new payee HydroOne Utility was successfully created.test]
at com.testcases.fail.TC003_VerifyAddPayee.VerifyAddPayee(TC003_VerifyAddPayee.java:49)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- VerifyAddPayee -->
</testsuite> <!-- Test -->
