<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Click to see Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target= "blank" href=VerifyAddPayee_06-12-2019 11:51:32.png>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target= "_blank" href=VerifyAddPayee_06-12-2019 11:51:32.png><img src=VerifyAddPayee_06-12-2019 11:51:32.png height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="12474" started-at="2019-12-06T23:51:20 EST" finished-at="2019-12-06T23:51:32 EST">
    <groups>
    </groups>
    <test name="Test" duration-ms="12474" started-at="2019-12-06T23:51:20 EST" finished-at="2019-12-06T23:51:32 EST">
      <class name="com.testcases.fail.TC003_VerifyAddPayee">
        <test-method status="FAIL" signature="VerifyAddPayee()[pri:3, instance:com.testcases.fail.TC003_VerifyAddPayee@55b53d44]" name="VerifyAddPayee" duration-ms="5571" started-at="2019-12-06T23:51:26 EST" finished-at="2019-12-06T23:51:32 EST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The new payee HydroOne Utility was successfully created.] but found [The new payee HydroOne Utility was successfully created.test]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The new payee HydroOne Utility was successfully created.] but found [The new payee HydroOne Utility was successfully created.test]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.testcases.fail.TC003_VerifyAddPayee.VerifyAddPayee(TC003_VerifyAddPayee.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target= "blank" href=VerifyAddPayee_06-12-2019 11:51:32.png>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target= "_blank" href=VerifyAddPayee_06-12-2019 11:51:32.png><img src=VerifyAddPayee_06-12-2019 11:51:32.png height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- VerifyAddPayee -->
      </class> <!-- com.testcases.fail.TC003_VerifyAddPayee -->
      <class name="com.testcases.fail.TC001_LoginTest">
        <test-method status="PASS" signature="loginTest()[pri:1, instance:com.testcases.fail.TC001_LoginTest@482bce4f]" name="loginTest" duration-ms="5804" started-at="2019-12-06T23:51:20 EST" finished-at="2019-12-06T23:51:26 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- com.testcases.fail.TC001_LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
