<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="4" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Click to see Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target= "blank" href=null-04-12-2019 1:49:26.png>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target= "_blank" href=null-04-12-2019 1:49:26.png><img src=null-04-12-2019 1:49:26.png height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[Click to see Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target= "blank" href=null-04-12-2019 1:49:26.png-04-12-2019 1:49:34.png>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target= "_blank" href=null-04-12-2019 1:49:26.png-04-12-2019 1:49:34.png><img src=null-04-12-2019 1:49:26.png-04-12-2019 1:49:34.png height=200 width=200></img></a>]]>
    </line>
    <line>
      <![CDATA[Click to see Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target= "blank" href=null-04-12-2019 1:49:26.png-04-12-2019 1:49:34.png-04-12-2019 1:49:39.png>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target= "_blank" href=null-04-12-2019 1:49:26.png-04-12-2019 1:49:34.png-04-12-2019 1:49:39.png><img src=null-04-12-2019 1:49:26.png-04-12-2019 1:49:34.png-04-12-2019 1:49:39.png height=200 width=200></img></a>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="18443" started-at="2019-12-04T01:49:20 EST" finished-at="2019-12-04T01:49:39 EST">
    <groups>
    </groups>
    <test name="Test" duration-ms="18443" started-at="2019-12-04T01:49:20 EST" finished-at="2019-12-04T01:49:39 EST">
      <class name="com.datadriven.testcases.LoginTest_DataDriven">
        <test-method status="FAIL" signature="login_datadriven(java.lang.String, java.lang.String)[pri:0, instance:com.datadriven.testcases.LoginTest_DataDriven@13b6aecc]" name="login_datadriven" duration-ms="5236" started-at="2019-12-04T01:49:20 EST" data-provider="Credential" finished-at="2019-12-04T01:49:26 EST">
          <params>
            <param index="0">
              <value>
                <![CDATA[pragya]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[maheshwari]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Zero - Log in> but was:<Zero - Account Summary>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Zero - Log in> but was:<Zero - Account Summary>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:82)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:87)
at com.datadriven.testcases.LoginTest_DataDriven.login_datadriven(LoginTest_DataDriven.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target= "blank" href=null-04-12-2019 1:49:26.png>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target= "_blank" href=null-04-12-2019 1:49:26.png><img src=null-04-12-2019 1:49:26.png height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- login_datadriven -->
        <test-method status="PASS" signature="login_datadriven(java.lang.String, java.lang.String)[pri:0, instance:com.datadriven.testcases.LoginTest_DataDriven@13b6aecc]" name="login_datadriven" duration-ms="4146" started-at="2019-12-04T01:49:27 EST" data-provider="Credential" finished-at="2019-12-04T01:49:31 EST">
          <params>
            <param index="0">
              <value>
                <![CDATA[username]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_datadriven -->
        <test-method status="FAIL" signature="login_datadriven(java.lang.String, java.lang.String)[pri:0, instance:com.datadriven.testcases.LoginTest_DataDriven@13b6aecc]" name="login_datadriven" duration-ms="3073" started-at="2019-12-04T01:49:31 EST" data-provider="Credential" finished-at="2019-12-04T01:49:34 EST">
          <params>
            <param index="0">
              <value>
                <![CDATA[username1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pssword]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Zero - Log in> but was:<Zero - Account Summary>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Zero - Log in> but was:<Zero - Account Summary>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:82)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:87)
at com.datadriven.testcases.LoginTest_DataDriven.login_datadriven(LoginTest_DataDriven.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target= "blank" href=null-04-12-2019 1:49:26.png-04-12-2019 1:49:34.png>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target= "_blank" href=null-04-12-2019 1:49:26.png-04-12-2019 1:49:34.png><img src=null-04-12-2019 1:49:26.png-04-12-2019 1:49:34.png height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- login_datadriven -->
        <test-method status="FAIL" signature="login_datadriven(java.lang.String, java.lang.String)[pri:0, instance:com.datadriven.testcases.LoginTest_DataDriven@13b6aecc]" name="login_datadriven" duration-ms="3636" started-at="2019-12-04T01:49:34 EST" data-provider="Credential" finished-at="2019-12-04T01:49:38 EST">
          <params>
            <param index="0">
              <value>
                <![CDATA[username]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password_12]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Zero - Log in> but was:<Zero - Account Summary>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Zero - Log in> but was:<Zero - Account Summary>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:82)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:87)
at com.datadriven.testcases.LoginTest_DataDriven.login_datadriven(LoginTest_DataDriven.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target= "blank" href=null-04-12-2019 1:49:26.png-04-12-2019 1:49:34.png-04-12-2019 1:49:39.png>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target= "_blank" href=null-04-12-2019 1:49:26.png-04-12-2019 1:49:34.png-04-12-2019 1:49:39.png><img src=null-04-12-2019 1:49:26.png-04-12-2019 1:49:34.png-04-12-2019 1:49:39.png height=200 width=200></img></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- login_datadriven -->
      </class> <!-- com.datadriven.testcases.LoginTest_DataDriven -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
